/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-06-07 12:39:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class updateSupporter_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(this, ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);

    try {
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"signup-form-container\">\r\n");
      out.write("<!-- action 채워넣기//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("	<form method=\"post\" action=\"\"\r\n");
      out.write("		class=\"woocommerce-form woocommerce-form-register register \">\r\n");
      out.write("		<p\r\n");
      out.write("			class=\"woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide more\">\r\n");
      out.write("			<label class=\"reg_signup\">이름&nbsp;</label>\r\n");
      out.write("<!-- 데이터불러온뒤 value수정//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("			<input type=\"text\"\r\n");
      out.write("				class=\"woocommerce-Input woocommerce-Input--text input-text\"\r\n");
      out.write("				name=\"supporter_name\" value=\"김개똥\" required>\r\n");
      out.write("		</p>\r\n");
      out.write("		<p\r\n");
      out.write("			class=\"woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide more\">\r\n");
      out.write("			<label class=\"reg_signup\">아이디&nbsp;</label>\r\n");
      out.write("<!-- 데이터불러온뒤 placeholder수정//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("			<input type=\"text\"\r\n");
      out.write("				class=\"woocommerce-Input woocommerce-Input--text input-text\"\r\n");
      out.write("				placeholder=\"dogpoo\" disabled=\"disabled\">\r\n");
      out.write("		</p>\r\n");
      out.write("\r\n");
      out.write("		<p\r\n");
      out.write("			class=\"woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide more\">\r\n");
      out.write("			<label class=\"reg_signup\">비밀번호&nbsp;</label>\r\n");
      out.write("<!-- id=\"pw1\"사용하여 ajax구현//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("			<input type=\"password\"\r\n");
      out.write("				class=\"woocommerce-Input woocommerce-Input--text input-text\"\r\n");
      out.write("				id=\"pw1\" name=\"supporter_password\" placeholder=\"비밀번호는 안전하게\" required>\r\n");
      out.write("		</p>\r\n");
      out.write("		<p\r\n");
      out.write("			class=\"woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide\"\r\n");
      out.write("			style=\"padding-left: 6px;\">\r\n");
      out.write("			<label class=\"reg_signup\">비밀번호확인&nbsp;</label>\r\n");
      out.write("<!-- id=\"pw1\"사용하여 ajax구현//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("			<input type=\"password\"\r\n");
      out.write("				class=\"woocommerce-Input woocommerce-Input--text input-text\"\r\n");
      out.write("				id=\"pw2\" required>\r\n");
      out.write("		</p>\r\n");
      out.write("		<h3 class=\"check-id-ps\">*비밀번호가 일치하지 않습니다.</h3>\r\n");
      out.write("\r\n");
      out.write("		<p\r\n");
      out.write("			class=\"woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide more\">\r\n");
      out.write("			<label class=\"reg_signup\">핸드폰번호&nbsp;</label>\r\n");
      out.write("<!-- 데이터불러온뒤 value수정//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("			<input type=\"text\"\r\n");
      out.write("				class=\"woocommerce-Input woocommerce-Input--text input-text\"\r\n");
      out.write("				name=\"phone_number\" value=\"01012459562\" required>\r\n");
      out.write("		</p>\r\n");
      out.write("		<p\r\n");
      out.write("			class=\"woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide more\">\r\n");
      out.write("			<label class=\"reg_signup\">우편주소&nbsp;</label>\r\n");
      out.write("<!-- 데이터불러온뒤 value수정//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("			<input type=\"text\"\r\n");
      out.write("				class=\"woocommerce-Input woocommerce-Input--text input-text unique post\"\r\n");
      out.write("				id=\"sample4_postcode\" name=\"post_code\" value=\"12345\" disabled=\"disabled\" required>\r\n");
      out.write("				<input type=\"button\" class=\"searchingPostcode\"\r\n");
      out.write("					onclick=\"sample4_execDaumPostcode()\"\r\n");
      out.write("					value=\"우편번호 찾기\">\r\n");
      out.write("				<mytag:postcode />\r\n");
      out.write("		</p>\r\n");
      out.write("		<p\r\n");
      out.write("			class=\"woocommerce-form-row woocommerce-form-row--wide form-row form-row-wide more bottom\">\r\n");
      out.write("			<label class=\"reg_signup\">상세주소&nbsp;</label>\r\n");
      out.write("<!-- 데이터불러온뒤 value수정//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("			<input type=\"text\"\r\n");
      out.write("				class=\"woocommerce-Input woocommerce-Input--text input-text\"\r\n");
      out.write("				name=\"detailed_address\" value=\"어딘가로\" required>\r\n");
      out.write("		</p>\r\n");
      out.write("		<p class=\"woocommerce-form-row form-row mb-0 register\">\r\n");
      out.write("			<button type=\"submit\" class=\"btn btn-primary btn-register\"\r\n");
      out.write("				formmethod=\"post\">수정하기</button>\r\n");
      out.write("		</p>\r\n");
      out.write("	</form>\r\n");
      out.write("</div>\r\n");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
