/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-06-12 09:52:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class animalsList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/나/Desktop/test2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/funny/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/tags/icon.tag", Long.valueOf(1655025110247L));
    _jspx_dependants.put("/WEB-INF/tags/pageHeader.tag", Long.valueOf(1655026127235L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1654357692724L));
    _jspx_dependants.put("/WEB-INF/tags/pageFooter.tag", Long.valueOf(1655026127235L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>입양하기</title>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      if (_jspx_meth_mytag_005ficon_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Gowun+Batang:wght@400;700&family=Jua&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Animate.css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("<!-- Icomoon Icon Fonts-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icomoon.css\">\r\n");
      out.write("<!-- Ion Icon Fonts-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/ionicons.min.css\">\r\n");
      out.write("<!-- Bootstrap  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Magnific Popup -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Flexslider  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/flexslider.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Owl Carousel -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Date Picker -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap-datepicker.css\">\r\n");
      out.write("<!-- Flaticons  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"fonts/flaticon/font/flaticon.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Theme style  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- contect animate.css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animalsList.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Material Icons -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"colorlib-loader\"></div>\r\n");
      out.write("	<div id=\"page\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Page Header-->\r\n");
      out.write("		");
      if (_jspx_meth_mytag_005fpageHeader_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		<div class=\"breadcrumbs\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col\">\r\n");
      out.write("						<p class=\"bread\">\r\n");
      out.write("<!-- href수정하기//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("							<span><a href=\"main.jsp\">HOME</a></span> / <span>입양하기</span>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<h1 id=\"menuTitle\">입양하기</h1>\r\n");
      out.write("\r\n");
      out.write("		<!-- select-animals -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"select-animals-container\">\r\n");
      out.write("			<form id=\"validate-form\" method=\"post\">\r\n");
      out.write("				<div class=\"row mb-1 mx-2\">\r\n");
      out.write("					<div class=\"col-lg-10\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-sm-12 col-lg mb-3 mb-lg-0\">\r\n");
      out.write("								<label class=\"d-block\"> <span\r\n");
      out.write("									class=\"h4 d-block text-dark font-weight-semi-bold mb-0\">동물구분</span>\r\n");
      out.write("									<small class=\"d-block text-secondary\">개/고양이</small>\r\n");
      out.write("								</label>\r\n");
      out.write("								<div class=\"js-form-message\">\r\n");
      out.write("									<div class=\"js-focus-state form-group\">\r\n");
      out.write("										<select name=\"animal_species\" class=\"form-control custom-select\"\r\n");
      out.write("											data-msg=\"동물구분을 선택해 주세요\" data-error-class=\"u-has-error\"\r\n");
      out.write("											data-success-class=\"u-has-success\">\r\n");
      out.write("											<option value=\"\">All</option>\r\n");
      out.write("\r\n");
      out.write("											<option value=\"개\">개</option>\r\n");
      out.write("											<option value=\"고양이\">고양이</option>\r\n");
      out.write("										</select>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-sm-12 col-lg mb-3 mb-lg-0\">\r\n");
      out.write("								<label class=\"d-block\"> <span\r\n");
      out.write("									class=\"h4 d-block text-dark font-weight-semi-bold mb-0\">성별</span>\r\n");
      out.write("									<small class=\"d-block text-secondary\">암컷/수컷</small>\r\n");
      out.write("								</label>\r\n");
      out.write("								<div class=\"js-form-message\">\r\n");
      out.write("									<div class=\"js-focus-state form-group\">\r\n");
      out.write("										<select name=\"animal_gender\" class=\"form-control custom-select\"\r\n");
      out.write("											data-msg=\"성별을 선택해 주세요\" data-error-class=\"u-has-error\"\r\n");
      out.write("											data-success-class=\"u-has-success\">\r\n");
      out.write("											<option value=\"\">All</option>\r\n");
      out.write("											<option value=\"암컷\">암컷</option>\r\n");
      out.write("											<option value=\"수컷\">수컷</option>\r\n");
      out.write("										</select>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-sm-12 col-lg mb-3 mb-lg-0\">\r\n");
      out.write("								<label class=\"d-block\"> <span\r\n");
      out.write("									class=\"h4 d-block text-dark font-weight-semi-bold mb-0\">크기</span>\r\n");
      out.write("									<small class=\"d-block text-secondary\">대/중/소 </small>\r\n");
      out.write("								</label>\r\n");
      out.write("								<div class=\"js-form-message\">\r\n");
      out.write("									<div class=\"js-focus-state form-group\">\r\n");
      out.write("										<select name=\"animal_weight\" class=\"form-control custom-select\"\r\n");
      out.write("											data-msg=\"크기을 선택해 주세요\" data-error-class=\"u-has-error\"\r\n");
      out.write("											data-success-class=\"u-has-success\">\r\n");
      out.write("<!-- value수정하기 (뭐라고 짓는게 나을까요)//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("											<option value=\"\">All</option>\r\n");
      out.write("											<option value=\"8\">소(8kg 미만)</option>\r\n");
      out.write("											<option value=\"818\">중(8~18kg 미만)</option>\r\n");
      out.write("											<option value=\"18\">대(18kg이상)</option>\r\n");
      out.write("										</select>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-sm-12 col-lg mb-3 mb-lg-0\">\r\n");
      out.write("								<label class=\"d-block\"> <span\r\n");
      out.write("									class=\"h4 d-block text-dark font-weight-semi-bold mb-0\">연령</span>\r\n");
      out.write("									<small class=\"d-block text-secondary\">puppy/junior/adult/senior</small>\r\n");
      out.write("								</label>\r\n");
      out.write("								<div class=\"js-form-message\">\r\n");
      out.write("									<div class=\"js-focus-state form-group\">\r\n");
      out.write("										<select name=\"animal_age\" class=\"form-control custom-select\"\r\n");
      out.write("											data-msg=\"연령을 선택해 주세요\" data-error-class=\"u-has-error\"\r\n");
      out.write("											data-success-class=\"u-has-success\">\r\n");
      out.write("<!-- value수정하기 (뭐라고 짓는게 나을까요)//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("											<option value=\"\">All</option>\r\n");
      out.write("											<option value=\"6\">Puppy(~ 6개월)</option>\r\n");
      out.write("											<option value=\"724\">Junior(7개월 ~ 2살)</option>\r\n");
      out.write("											<option value=\"3696\">Adult(3살 ~ 8살)</option>\r\n");
      out.write("											<option value=\"108\">Senior(9살 ~)</option>\r\n");
      out.write("										</select>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"col-12 g-pt-15\">\r\n");
      out.write("								<div class=\"input-group\">\r\n");
      out.write("									<input type=\"text\" class=\"form-control\" name=\"keyword\" id=\"name\"\r\n");
      out.write("										placeholder=\"이름 (이름을 모를경우 비워두셔도 됩니다.)\" >\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-lg-2 g-pt-30 g-pt-60--lg search\">\r\n");
      out.write("						<div class=\"g-pb-15 g-pb-sm-0 search-refresh\">\r\n");
      out.write("<!-- href수정하기//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("							<a href=\"animalsList.jsp\"\r\n");
      out.write("								class=\"btn btn-sm btn-block g-brd-0 text-secondary g-font-size-14 g-px-0 mb-1 reset\">\r\n");
      out.write("								<i class=\"icon-refresh\"></i> <span\r\n");
      out.write("								class=\"g-text-underline search-refresh\">검색 설정 초기화</span>\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"g-pt-15--lg\">\r\n");
      out.write("							<button type=\"submit\"\r\n");
      out.write("								class=\"btn btn-sm btn-block btn-primary btn-search-animals\">검색</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- animals list -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"row animals-photos\">\r\n");
      out.write("<!-- 값들 수정//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("<!-- 데이터 불러온뒤 for문으로 구현//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("			<div class=\"col-md-3 col-lg-3 mb-4 text-center animals-photos-text\">\r\n");
      out.write("				<div class=\"product-entry border\">\r\n");
      out.write("<!-- href 수정//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("					<a href=\"animalOne.jsp\" class=\"prod-img\">\r\n");
      out.write("<!-- src 수정//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("					<img src=\"images_sample/강록.png\"\r\n");
      out.write("						class=\"img-fluid animals\" alt=\"Free html5 bootstrap 4 template\">\r\n");
      out.write("					</a>\r\n");
      out.write("					<div class=\"desc\">\r\n");
      out.write("						<h2>\r\n");
      out.write("<!-- href 수정//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("<!-- 데이터 수정//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("							<a href=\"animalOne.jsp\">강록</a>\r\n");
      out.write("						</h2>\r\n");
      out.write("						<span class=\"animal_spacies\">개</span><br> <span\r\n");
      out.write("							class=\"animal_gender\">수컷(중성화O)</span><br> <span\r\n");
      out.write("							class=\"animal_age\">2살 4개월 <span class=\"animal_weight\">/\r\n");
      out.write("								21.0kg</span></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("<!-- 페이지 채우기 용//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("			<div class=\"col-md-3 col-lg-3 mb-4 text-center\">\r\n");
      out.write("				<div class=\"product-entry border\">\r\n");
      out.write("					<a href=\"animalOne.jsp\" class=\"prod-img\"> <img src=\"images_sample/남희.png\"\r\n");
      out.write("						class=\"img-fluid animals\" alt=\"Free html5 bootstrap 4 template\">\r\n");
      out.write("					</a>\r\n");
      out.write("					<div class=\"desc\">\r\n");
      out.write("						<h2>\r\n");
      out.write("							<a href=\"animalOne.jsp\">남희</a>\r\n");
      out.write("						</h2>\r\n");
      out.write("						<span class=\"animal_spacies\">개</span><br> <span\r\n");
      out.write("							class=\"animal_gender\">암컷(중성화O)</span><br> <span\r\n");
      out.write("							class=\"animal_age\">6개월 <span class=\"animal_weight\">/\r\n");
      out.write("								6.5kg</span></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-md-3 col-lg-3 mb-4 text-center\">\r\n");
      out.write("				<div class=\"product-entry border\">\r\n");
      out.write("					<a href=\"animalOne.jsp\" class=\"prod-img\"> <img src=\"images_sample/레슬리.png\"\r\n");
      out.write("						class=\"img-fluid animals\" alt=\"Free html5 bootstrap 4 template\">\r\n");
      out.write("					</a>\r\n");
      out.write("					<div class=\"desc\">\r\n");
      out.write("						<h2>\r\n");
      out.write("							<a href=\"animalOne.jsp\">레슬리</a>\r\n");
      out.write("						</h2>\r\n");
      out.write("						<span class=\"animal_spacies\">개</span><br> <span\r\n");
      out.write("							class=\"animal_gender\">수컷(중성화O)</span><br> <span\r\n");
      out.write("							class=\"animal_age\">1살 2개월 <span class=\"animal_weight\">/\r\n");
      out.write("								7.9kg</span></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-md-3 col-lg-3 mb-4 text-center\">\r\n");
      out.write("				<div class=\"product-entry border\">\r\n");
      out.write("					<a href=\"animalOne.jsp\" class=\"prod-img\"> <img src=\"images_sample/루시.png\"\r\n");
      out.write("						class=\"img-fluid animals\" alt=\"Free html5 bootstrap 4 template\">\r\n");
      out.write("					</a>\r\n");
      out.write("					<div class=\"desc\">\r\n");
      out.write("						<h2>\r\n");
      out.write("							<a href=\"animalOne.jsp\">루시</a>\r\n");
      out.write("						</h2>\r\n");
      out.write("						<span class=\"animal_spacies\">개</span><br> <span\r\n");
      out.write("							class=\"animal_gender\">암컷(중성화O)</span><br> <span\r\n");
      out.write("							class=\"animal_age\">4살 2개월 <span class=\"animal_weight\">/\r\n");
      out.write("								7.5kg</span></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-md-3 col-lg-3 mb-4 text-center\">\r\n");
      out.write("				<div class=\"product-entry border\">\r\n");
      out.write("					<a href=\"animalOne.jsp\" class=\"prod-img\"> <img src=\"images_sample/마리.png\"\r\n");
      out.write("						class=\"img-fluid animals\" alt=\"Free html5 bootstrap 4 template\">\r\n");
      out.write("					</a>\r\n");
      out.write("					<div class=\"desc\">\r\n");
      out.write("						<h2>\r\n");
      out.write("							<a href=\"animalOne.jsp\">마리</a>\r\n");
      out.write("						</h2>\r\n");
      out.write("						<span class=\"animal_spacies\">고양이</span><br> <span\r\n");
      out.write("							class=\"animal_gender\">암컷(중성화O)</span><br> <span\r\n");
      out.write("							class=\"animal_age\">5살 10개월 <span class=\"animal_weight\">/\r\n");
      out.write("								4.6kg</span></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-md-3 col-lg-3 mb-4 text-center\">\r\n");
      out.write("				<div class=\"product-entry border\">\r\n");
      out.write("					<a href=\"animalOne.jsp\" class=\"prod-img\"> <img src=\"images_sample/쿠로.png\"\r\n");
      out.write("						class=\"img-fluid animals\" alt=\"Free html5 bootstrap 4 template\">\r\n");
      out.write("					</a>\r\n");
      out.write("					<div class=\"desc\">\r\n");
      out.write("						<h2>\r\n");
      out.write("							<a href=\"animalOne.jsp\">쿠로</a>\r\n");
      out.write("						</h2>\r\n");
      out.write("						<span class=\"animal_spacies\">고양이</span><br> <span\r\n");
      out.write("							class=\"animal_gender\">수컷(중성화)</span><br> <span\r\n");
      out.write("							class=\"animal_age\">4살 1개월<span class=\"animal_weight\">/\r\n");
      out.write("								2.8kg</span></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-md-3 col-lg-3 mb-4 text-center\">\r\n");
      out.write("				<div class=\"product-entry border\">\r\n");
      out.write("					<a href=\"animalOne.jsp\" class=\"prod-img\"> <img src=\"images_sample/홀리.png\"\r\n");
      out.write("						class=\"img-fluid animals\" alt=\"Free html5 bootstrap 4 template\">\r\n");
      out.write("					</a>\r\n");
      out.write("					<div class=\"desc\">\r\n");
      out.write("						<h2>\r\n");
      out.write("							<a href=\"animalOne.jsp\">홀리</a>\r\n");
      out.write("						</h2>\r\n");
      out.write("						<span class=\"animal_spacies\">고양이</span><br> <span\r\n");
      out.write("							class=\"animal_gender\">암컷(중성화O)</span><br> <span\r\n");
      out.write("							class=\"animal_age\">8살 1개월 <span class=\"animal_weight\">/\r\n");
      out.write("								5.1kg</span></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-md-3 col-lg-3 mb-4 text-center\">\r\n");
      out.write("				<div class=\"product-entry border\">\r\n");
      out.write("					<a href=\"animalOne.jsp\" class=\"prod-img\"> <img src=\"images_sample/보석.jpg\"\r\n");
      out.write("						class=\"img-fluid animals\" alt=\"Free html5 bootstrap 4 template\">\r\n");
      out.write("					</a>\r\n");
      out.write("					<div class=\"desc\">\r\n");
      out.write("						<h2>\r\n");
      out.write("							<a href=\"animalOne.jsp\">보석</a>\r\n");
      out.write("						</h2>\r\n");
      out.write("						<span class=\"animal_spacies\">개(믹스)</span><br> <span\r\n");
      out.write("							class=\"animal_gender\">수컷(중성화O)</span><br> <span\r\n");
      out.write("							class=\"animal_age\">10살 2개월 <span class=\"animal_weight\">/\r\n");
      out.write("								3.3kg</span></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("<!-- 여기까지 페이지 채우기 용//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("		</div>\r\n");
      out.write("<!-- 페이지네이션 구현한다면 유지//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("		<div class=\"pagenation\">\r\n");
      out.write("			<div class=\"col-md-12 text-center\">\r\n");
      out.write("				<div class=\"block-27\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\"><i class=\"ion-ios-arrow-back\"></i></a></li>\r\n");
      out.write("						<li class=\"active\"><span>1</span></li>\r\n");
      out.write("						<li><a href=\"#\">2</a></li>\r\n");
      out.write("						<li><a href=\"#\">3</a></li>\r\n");
      out.write("						<li><a href=\"#\">4</a></li>\r\n");
      out.write("						<li><a href=\"#\">5</a></li>\r\n");
      out.write("						<li><a href=\"#\"><i class=\"ion-ios-arrow-forward\"></i></a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Page Footer-->\r\n");
      out.write("		");
      if (_jspx_meth_mytag_005fpageFooter_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"gototop js-top\">\r\n");
      out.write("		<a href=\"#\" class=\"js-gotop\"><i class=\"ion-ios-arrow-up\"></i></a>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- jQuery -->\r\n");
      out.write("	<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("	<!-- popper -->\r\n");
      out.write("	<script src=\"js/popper.min.js\"></script>\r\n");
      out.write("	<!-- bootstrap 4.1 -->\r\n");
      out.write("	<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("	<!-- jQuery easing -->\r\n");
      out.write("	<script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("	<!-- Waypoints -->\r\n");
      out.write("	<script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("	<!-- Flexslider -->\r\n");
      out.write("	<script src=\"js/jquery.flexslider-min.js\"></script>\r\n");
      out.write("	<!-- Owl carousel -->\r\n");
      out.write("	<script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("	<!-- Magnific Popup -->\r\n");
      out.write("	<script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("	<script src=\"js/magnific-popup-options.js\"></script>\r\n");
      out.write("	<!-- Date Picker -->\r\n");
      out.write("	<script src=\"js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("	<!-- Stellar Parallax -->\r\n");
      out.write("	<script src=\"js/jquery.stellar.min.js\"></script>\r\n");
      out.write("	<!-- Main -->\r\n");
      out.write("	<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_mytag_005ficon_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mytag:icon
    org.apache.jsp.tag.web.icon_tag _jspx_th_mytag_005ficon_005f0 = new org.apache.jsp.tag.web.icon_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mytag_005ficon_005f0);
    try {
      _jspx_th_mytag_005ficon_005f0.setJspContext(_jspx_page_context);
      _jspx_th_mytag_005ficon_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mytag_005ficon_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_mytag_005fpageHeader_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mytag:pageHeader
    org.apache.jsp.tag.web.pageHeader_tag _jspx_th_mytag_005fpageHeader_005f0 = new org.apache.jsp.tag.web.pageHeader_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mytag_005fpageHeader_005f0);
    try {
      _jspx_th_mytag_005fpageHeader_005f0.setJspContext(_jspx_page_context);
      _jspx_th_mytag_005fpageHeader_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mytag_005fpageHeader_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_mytag_005fpageFooter_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mytag:pageFooter
    org.apache.jsp.tag.web.pageFooter_tag _jspx_th_mytag_005fpageFooter_005f0 = new org.apache.jsp.tag.web.pageFooter_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mytag_005fpageFooter_005f0);
    try {
      _jspx_th_mytag_005fpageFooter_005f0.setJspContext(_jspx_page_context);
      _jspx_th_mytag_005fpageFooter_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mytag_005fpageFooter_005f0);
    }
    return false;
  }
}
