/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-06-07 11:43:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardRequest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/tags/icon.tag", Long.valueOf(1654602076086L));
    _jspx_dependants.put("/WEB-INF/tags/pageHeader.tag", Long.valueOf(1654602076144L));
    _jspx_dependants.put("/WEB-INF/tags/pageFooter.tag", Long.valueOf(1654602076137L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>봉사신청</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      if (_jspx_meth_mytag_005ficon_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Gowun+Batang:wght@400;700&family=Jua&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Animate.css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("<!-- Icomoon Icon Fonts-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icomoon.css\">\r\n");
      out.write("<!-- Ion Icon Fonts-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/ionicons.min.css\">\r\n");
      out.write("<!-- Bootstrap  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Magnific Popup -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Flexslider  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/flexslider.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Owl Carousel -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Date Picker -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap-datepicker.css\">\r\n");
      out.write("<!-- Flaticons  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"fonts/flaticon/font/flaticon.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Theme style  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"colorlib-loader\"></div>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"page\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Page Header-->\r\n");
      out.write("		");
      if (_jspx_meth_mytag_005fpageHeader_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		<div class=\"breadcrumbs\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col\">\r\n");
      out.write("						<p class=\"bread\">\r\n");
      out.write("<!-- href수정하기//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("							<span><a href=\"boardList.jsp\">봉사자모집</a></span> / <span>봉사신청</span>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<h1 id=\"menuTitle\">봉사신청</h1>\r\n");
      out.write("		<hr>\r\n");
      out.write("\r\n");
      out.write("		<div style=\"text-align: center; margin-top: 2em; margin-bottom: 7em;\">\r\n");
      out.write("			<div class=\"col-sm-4 text-left total writeForm\"\r\n");
      out.write("				style=\"display: inline-block;\">\r\n");
      out.write("<!-- action수정하기//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("<!-- 카테고리는 관리자 아니라면 자동으로 '일반' 설정//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("				<form action=\"boardDone.jsp\" method=\"post\">\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<h5>제목</h5>\r\n");
      out.write("						<input type=\"text\" class=\"form-control gap\"\r\n");
      out.write("							placeholder=\"제목을 입력해 주세요.\" name=\"board_title\">\r\n");
      out.write("\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<h5>신청 내용</h5>\r\n");
      out.write("							<textarea name=\"board_content\" cols=\"30\" rows=\"10\"\r\n");
      out.write("								class=\"form-control gap\" placeholder=\"희망 날짜와 시간을 반드시 포함해주세요.\"></textarea>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<input type=\"submit\" value=\"글 작성하기\"\r\n");
      out.write("						class=\"btn btn-primary inputSubmit\">\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Page Footer-->\r\n");
      out.write("		");
      if (_jspx_meth_mytag_005fpageFooter_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"gototop js-top\">\r\n");
      out.write("		<a href=\"#\" class=\"js-gotop\"><i class=\"ion-ios-arrow-up\"></i></a>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- jQuery -->\r\n");
      out.write("	<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("	<!-- popper -->\r\n");
      out.write("	<script src=\"js/popper.min.js\"></script>\r\n");
      out.write("	<!-- bootstrap 4.1 -->\r\n");
      out.write("	<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("	<!-- jQuery easing -->\r\n");
      out.write("	<script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("	<!-- Waypoints -->\r\n");
      out.write("	<script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("	<!-- Flexslider -->\r\n");
      out.write("	<script src=\"js/jquery.flexslider-min.js\"></script>\r\n");
      out.write("	<!-- Owl carousel -->\r\n");
      out.write("	<script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("	<!-- Magnific Popup -->\r\n");
      out.write("	<script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("	<script src=\"js/magnific-popup-options.js\"></script>\r\n");
      out.write("	<!-- Date Picker -->\r\n");
      out.write("	<script src=\"js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("	<!-- Stellar Parallax -->\r\n");
      out.write("	<script src=\"js/jquery.stellar.min.js\"></script>\r\n");
      out.write("	<!-- Main -->\r\n");
      out.write("	<script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_mytag_005ficon_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mytag:icon
    org.apache.jsp.tag.web.icon_tag _jspx_th_mytag_005ficon_005f0 = new org.apache.jsp.tag.web.icon_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mytag_005ficon_005f0);
    try {
      _jspx_th_mytag_005ficon_005f0.setJspContext(_jspx_page_context);
      _jspx_th_mytag_005ficon_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mytag_005ficon_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_mytag_005fpageHeader_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mytag:pageHeader
    org.apache.jsp.tag.web.pageHeader_tag _jspx_th_mytag_005fpageHeader_005f0 = new org.apache.jsp.tag.web.pageHeader_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mytag_005fpageHeader_005f0);
    try {
      _jspx_th_mytag_005fpageHeader_005f0.setJspContext(_jspx_page_context);
      _jspx_th_mytag_005fpageHeader_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mytag_005fpageHeader_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_mytag_005fpageFooter_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mytag:pageFooter
    org.apache.jsp.tag.web.pageFooter_tag _jspx_th_mytag_005fpageFooter_005f0 = new org.apache.jsp.tag.web.pageFooter_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mytag_005fpageFooter_005f0);
    try {
      _jspx_th_mytag_005fpageFooter_005f0.setJspContext(_jspx_page_context);
      _jspx_th_mytag_005fpageFooter_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mytag_005fpageFooter_005f0);
    }
    return false;
  }
}
