/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.63
 * Generated at: 2022-06-12 09:53:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class support_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/나/Desktop/test2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/funny/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/tags/icon.tag", Long.valueOf(1655025110247L));
    _jspx_dependants.put("/WEB-INF/tags/pageHeader.tag", Long.valueOf(1655026127235L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1654357692724L));
    _jspx_dependants.put("/WEB-INF/tags/pageFooter.tag", Long.valueOf(1655026127235L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>후원하기</title>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      if (_jspx_meth_mytag_005ficon_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Gowun+Batang:wght@400;700&family=Jua&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Animate.css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("<!-- Icomoon Icon Fonts-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/icomoon.css\">\r\n");
      out.write("<!-- Ion Icon Fonts-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/ionicons.min.css\">\r\n");
      out.write("<!-- Bootstrap  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Magnific Popup -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Flexslider  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/flexslider.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Owl Carousel -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Date Picker -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap-datepicker.css\">\r\n");
      out.write("<!-- Flaticons  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"fonts/flaticon/font/flaticon.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Theme style  -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- contect signup.css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/support.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Material Icons -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<div class=\"colorlib-loader\"></div>\r\n");
      out.write("<div id=\"page\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Page Header-->\r\n");
      out.write("	");
      if (_jspx_meth_mytag_005fpageHeader_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<div class=\"breadcrumbs\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col\">\r\n");
      out.write("					<p class=\"bread\">\r\n");
      out.write("						<!-- href수정하기//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("						<span><a href=\"main.jsp\">HOME</a></span> / <span>후원하기</span>\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<h1 id=\"menuTitle\">후원하기</h1>\r\n");
      out.write("	<hr>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"twin container support\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-md-6\" style=\"padding-left: 15em;\">\r\n");
      out.write("				<div class=\"twins-wrap\">\r\n");
      out.write("					<h2 class=\"sub-title\">정기후원</h2>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div></div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h5 class=\"subscript\">\r\n");
      out.write("						매달 약정된 금액을 후원하여<br>다양한 영역에서의<br>캠페인과 문화 영역에서의 활동 등<br>봄365의\r\n");
      out.write("						전반적인 활동과 운영을<br>지지해 주실 수 있습니다.\r\n");
      out.write("					</h5>\r\n");
      out.write("					<!-- href수정하기//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("					<a href=\"supportREGRequest.jsp\" class=\"btn btn-primary support\">&nbsp;후원하기&nbsp;</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-6\" style=\"padding-right: 15em;\">\r\n");
      out.write("				<div class=\"twins-wrap\">\r\n");
      out.write("					<h2 class=\"sub-title\">일시후원</h2>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div></div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<h5 class=\"subscript\">\r\n");
      out.write("						반려동물의 생일이나 입양일 등<br>소중한 날을 기념하여<br>동물들에게 사랑을 전해주세요.<br>한\r\n");
      out.write("						번의 따뜻한 사랑이<br>큰 기적을 이루게 됩니다.\r\n");
      out.write("					</h5>\r\n");
      out.write("					<!-- href수정하기//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->\r\n");
      out.write("					<a href=\"supportTEMRequest.jsp\" class=\"btn btn-primary support\">&nbsp;후원하기&nbsp;</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<hr style=\"margin-top: 0;\">\r\n");
      out.write("	<h3 class=\"h3support\">후원금은 이렇게 사용됩니다</h3>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"row row-pb-md support\">\r\n");
      out.write("			<div class=\"col footer-col colorlib-widget\">\r\n");
      out.write("				<img src=\"images_sample/supportEX1.jpg\" class=\"img-fluid animals\"\r\n");
      out.write("					alt=\"Free html5 bootstrap 4 template\">\r\n");
      out.write("				<h4>보호 · 입양</h4>\r\n");
      out.write("				<p>봄365가 구조한 동물들은 센터로 입소하여 살처분의 위험 없이 청결한 환경에서 따뜻한 보살핌을 받습니다.\r\n");
      out.write("					동물들은 봄365의 엄격한 입양심사를 통해 평생가족을 찾습니다.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col footer-col colorlib-widget\">\r\n");
      out.write("				<img src=\"images_sample/supportEX2.jpg\" class=\"img-fluid animals\"\r\n");
      out.write("					alt=\"Free html5 bootstrap 4 template\">\r\n");
      out.write("				<h4>구조 · 구호</h4>\r\n");
      out.write("				<p>긴급한 도움이 필요한 동물들을 구조하고, 시민들이 구조한 동물의 치료와 입양을 지원합니다. 사설보호소 지원 및\r\n");
      out.write("					봉사, 중성화수술과 사료지원 등 구호활동을 함께합니다.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col footer-col colorlib-widget\">\r\n");
      out.write("				<img src=\"images_sample/supportEX3.jpg\" class=\"img-fluid animals\"\r\n");
      out.write("					alt=\"Free html5 bootstrap 4 template\">\r\n");
      out.write("				<h4>아카이빙</h4>\r\n");
      out.write("				<p>동물권 자료와 기록을 보관하고 공유합니다. 동물과 동물권 활동에 대한 정보 공유는 보다 건설적이고 건강한\r\n");
      out.write("					동물권 성립을 위한 시민활동의 자양분이 되고 있습니다.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\" style=\"margin-bottom: 14em;\">\r\n");
      out.write("		<div class=\"row row-pb-md support\">\r\n");
      out.write("			<div class=\"col footer-col colorlib-widget\">\r\n");
      out.write("				<img src=\"images_sample/supportEX4.jpg\" class=\"img-fluid animals\"\r\n");
      out.write("					alt=\"Free html5 bootstrap 4 template\">\r\n");
      out.write("				<h4>문화활동 및 캠페인</h4>\r\n");
      out.write("				<p>동물영화제·전시회·인문사회 프로그램 등을 통해 생명존중 의식 확장의 장을 마련하여 시민과 함께하는 다양한\r\n");
      out.write("					활동으로 성숙한 시민사회를 도모합니다.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col footer-col colorlib-widget\">\r\n");
      out.write("				<img src=\"images_sample/supportEX5.jpg\" class=\"img-fluid animals\"\r\n");
      out.write("					alt=\"Free html5 bootstrap 4 template\">\r\n");
      out.write("				<h4>법 · 정책 연구 및 제안</h4>\r\n");
      out.write("				<p>모든 동물의 권리를 보장하기 위해 법과 정책을 연구하고 제안합니다. 동물보호법 강화와 더불어 동물권을 헌법에\r\n");
      out.write("					명시하기 위한 활동을 전개합니다.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col footer-col colorlib-widget\">\r\n");
      out.write("				<img src=\"images_sample/supportEX6.jpg\" class=\"img-fluid animals\"\r\n");
      out.write("					alt=\"Free html5 bootstrap 4 template\">\r\n");
      out.write("				<h4>학대대응</h4>\r\n");
      out.write("				<p>학대행위에 고발조치를 취하고, 동물보호법의 사각지대에 있는 동물들을 구제하기 위한 전략을 수립하여 정부기관과\r\n");
      out.write("					협력해 동물학대가 발생하지 않도록 앞장서고 있습니다.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Page Footer-->\r\n");
      out.write("	");
      if (_jspx_meth_mytag_005fpageFooter_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"gototop js-top\">\r\n");
      out.write("	<a href=\"#\" class=\"js-gotop\"><i class=\"ion-ios-arrow-up\"></i></a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<!-- popper -->\r\n");
      out.write("<script src=\"js/popper.min.js\"></script>\r\n");
      out.write("<!-- bootstrap 4.1 -->\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- jQuery easing -->\r\n");
      out.write("<script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("<!-- Waypoints -->\r\n");
      out.write("<script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("<!-- Flexslider -->\r\n");
      out.write("<script src=\"js/jquery.flexslider-min.js\"></script>\r\n");
      out.write("<!-- Owl carousel -->\r\n");
      out.write("<script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("<!-- Magnific Popup -->\r\n");
      out.write("<script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("<script src=\"js/magnific-popup-options.js\"></script>\r\n");
      out.write("<!-- Date Picker -->\r\n");
      out.write("<script src=\"js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("<!-- Stellar Parallax -->\r\n");
      out.write("<script src=\"js/jquery.stellar.min.js\"></script>\r\n");
      out.write("<!-- Main -->\r\n");
      out.write("<script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_mytag_005ficon_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mytag:icon
    org.apache.jsp.tag.web.icon_tag _jspx_th_mytag_005ficon_005f0 = new org.apache.jsp.tag.web.icon_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mytag_005ficon_005f0);
    try {
      _jspx_th_mytag_005ficon_005f0.setJspContext(_jspx_page_context);
      _jspx_th_mytag_005ficon_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mytag_005ficon_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_mytag_005fpageHeader_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mytag:pageHeader
    org.apache.jsp.tag.web.pageHeader_tag _jspx_th_mytag_005fpageHeader_005f0 = new org.apache.jsp.tag.web.pageHeader_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mytag_005fpageHeader_005f0);
    try {
      _jspx_th_mytag_005fpageHeader_005f0.setJspContext(_jspx_page_context);
      _jspx_th_mytag_005fpageHeader_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mytag_005fpageHeader_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_mytag_005fpageFooter_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  mytag:pageFooter
    org.apache.jsp.tag.web.pageFooter_tag _jspx_th_mytag_005fpageFooter_005f0 = new org.apache.jsp.tag.web.pageFooter_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_mytag_005fpageFooter_005f0);
    try {
      _jspx_th_mytag_005fpageFooter_005f0.setJspContext(_jspx_page_context);
      _jspx_th_mytag_005fpageFooter_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_mytag_005fpageFooter_005f0);
    }
    return false;
  }
}
